export type AgentStatus = 'queued' | 'active' | 'completed'

export interface Agent {
  id: string
  name: string
  category: string
  status: AgentStatus
  currentTask?: string
  startedAt?: string
  completedAt?: string
}

export const ALL_AGENTS: Omit<Agent, 'status'>[] = [
  { id: 'academic-coach', name: 'Academic Coach', category: 'Education' },
  { id: 'ad-creative', name: 'Ad Creative', category: 'Advertising' },
  { id: 'ad-mockup-builder', name: 'Ad Mockup Builder', category: 'Advertising' },
  { id: 'ad-scriptwriter', name: 'Ad Scriptwriter', category: 'Advertising' },
  { id: 'affiliate-marketing-agent', name: 'Affiliate Marketing', category: 'Marketing' },
  { id: 'agent-builder', name: 'Agent Builder', category: 'Platform' },
  { id: 'agent-debugger', name: 'Agent Debugger', category: 'Platform' },
  { id: 'agent-editor', name: 'Agent Editor', category: 'Platform' },
  { id: 'agent-tester', name: 'Agent Tester', category: 'Platform' },
  { id: 'ai-prompt-engineer', name: 'AI Prompt Engineer', category: 'Platform' },
  { id: 'analytics-review', name: 'Analytics Review', category: 'Analytics' },
  { id: 'api-integrator', name: 'API Integrator', category: 'Engineering' },
  { id: 'audience-insights', name: 'Audience Insights', category: 'Research' },
  { id: 'audience-intelligence', name: 'Audience Intelligence', category: 'Research' },
  { id: 'automation-builder', name: 'Automation Builder', category: 'Engineering' },
  { id: 'brand-deals-agent', name: 'Brand Deals', category: 'Partnerships' },
  { id: 'brand-kit-builder', name: 'Brand Kit Builder', category: 'Creative' },
  { id: 'brand-safety-agent', name: 'Brand Safety', category: 'Compliance' },
  { id: 'brand-voice', name: 'Brand Voice', category: 'Creative' },
  { id: 'business-plan-writer', name: 'Business Plan Writer', category: 'Strategy' },
  { id: 'campaign-strategy', name: 'Campaign Strategy', category: 'Marketing' },
  { id: 'case-study-builder', name: 'Case Study Builder', category: 'Content' },
  { id: 'community-manager', name: 'Community Manager', category: 'Social' },
  { id: 'competitive-intel', name: 'Competitive Intel', category: 'Research' },
  { id: 'compliance-checker', name: 'Compliance Checker', category: 'Compliance' },
  { id: 'content-repurposer', name: 'Content Repurposer', category: 'Content' },
  { id: 'content-scheduler', name: 'Content Scheduler', category: 'Operations' },
  { id: 'context-switcher', name: 'Context Switcher', category: 'Platform' },
  { id: 'copywriter', name: 'Copywriter', category: 'Creative' },
  { id: 'course-builder', name: 'Course Builder', category: 'Education' },
  { id: 'creative-gallery-agent', name: 'Creative Gallery', category: 'Creative' },
  { id: 'creative-review', name: 'Creative Review', category: 'Creative' },
  { id: 'crisis-comms-agent', name: 'Crisis Comms', category: 'PR' },
  { id: 'daily-briefing-agent', name: 'Daily Briefing', category: 'Operations' },
  { id: 'data-analyst', name: 'Data Analyst', category: 'Analytics' },
  { id: 'database-architect', name: 'Database Architect', category: 'Engineering' },
  { id: 'debate-prep-agent', name: 'Debate Prep', category: 'Education' },
  { id: 'devops-agent', name: 'DevOps Agent', category: 'Engineering' },
  { id: 'documents-agent', name: 'Documents Agent', category: 'Operations' },
  { id: 'email-marketing', name: 'Email Marketing', category: 'Marketing' },
  { id: 'event-marketing-agent', name: 'Event Marketing', category: 'Marketing' },
  { id: 'exam-prep-agent', name: 'Exam Prep', category: 'Education' },
  { id: 'funding-researcher', name: 'Funding Researcher', category: 'Research' },
  { id: 'github-manager', name: 'GitHub Manager', category: 'Engineering' },
  { id: 'global-expansion-researcher', name: 'Global Expansion', category: 'Research' },
  { id: 'image-analyzer', name: 'Image Analyzer', category: 'Creative' },
  { id: 'instagram-analytics-agent', name: 'Instagram Analytics', category: 'Analytics' },
  { id: 'instagram-strategist', name: 'Instagram Strategist', category: 'Social' },
  { id: 'international-markets-agent', name: 'International Markets', category: 'Research' },
  { id: 'knowledge-base-curator', name: 'Knowledge Base Curator', category: 'Memory' },
  { id: 'knowledge-graph', name: 'Knowledge Graph', category: 'Memory' },
  { id: 'learning-engine', name: 'Learning Engine', category: 'Memory' },
  { id: 'legal-plain-english', name: 'Legal Plain English', category: 'Compliance' },
  { id: 'linkedin-strategist', name: 'LinkedIn Strategist', category: 'Social' },
  { id: 'local-marketing-agent', name: 'Local Marketing', category: 'Marketing' },
  { id: 'local-seo-agent', name: 'Local SEO', category: 'SEO' },
  { id: 'mac-agent', name: 'Mac Agent', category: 'Platform' },
  { id: 'market-entry-strategist', name: 'Market Entry Strategist', category: 'Strategy' },
  { id: 'market-research', name: 'Market Research', category: 'Research' },
  { id: 'memory-curator', name: 'Memory Curator', category: 'Memory' },
  { id: 'merch-strategist', name: 'Merch Strategist', category: 'Strategy' },
  { id: 'mission-memory', name: 'Mission Memory', category: 'Memory' },
  { id: 'mission-planner', name: 'Mission Planner', category: 'Operations' },
  { id: 'mission-reviewer', name: 'Mission Reviewer', category: 'Operations' },
  { id: 'mobile-app-planner', name: 'Mobile App Planner', category: 'Engineering' },
  { id: 'mockup-designer', name: 'Mockup Designer', category: 'Creative' },
  { id: 'monetization-strategist', name: 'Monetization Strategist', category: 'Strategy' },
  { id: 'news-monitor', name: 'News Monitor', category: 'Research' },
  { id: 'newsletter-builder', name: 'Newsletter Builder', category: 'Content' },
  { id: 'ops-manager', name: 'Ops Manager', category: 'Operations' },
  { id: 'paid-ads-manager', name: 'Paid Ads Manager', category: 'Advertising' },
  { id: 'paper-writer', name: 'Paper Writer', category: 'Education' },
  { id: 'partnerships-agent', name: 'Partnerships', category: 'Partnerships' },
  { id: 'personal-brand-strategist', name: 'Personal Brand Strategist', category: 'Strategy' },
  { id: 'pitch-deck-builder', name: 'Pitch Deck Builder', category: 'Strategy' },
  { id: 'podcast-monitor', name: 'Podcast Monitor', category: 'Research' },
  { id: 'podcast-producer', name: 'Podcast Producer', category: 'Content' },
  { id: 'podcast-scriptwriter', name: 'Podcast Scriptwriter', category: 'Content' },
  { id: 'pr-media-agent', name: 'PR & Media', category: 'PR' },
  { id: 'preference-memory', name: 'Preference Memory', category: 'Memory' },
  { id: 'presentation-builder', name: 'Presentation Builder', category: 'Content' },
  { id: 'pricing-strategist', name: 'Pricing Strategist', category: 'Strategy' },
  { id: 'professor-perspective-agent', name: 'Professor Perspective', category: 'Education' },
  { id: 'reddit-monitor', name: 'Reddit Monitor', category: 'Research' },
  { id: 'reels-scriptwriter', name: 'Reels Scriptwriter', category: 'Content' },
  { id: 'research-synthesizer', name: 'Research Synthesizer', category: 'Research' },
  { id: 'sales-scriptwriter', name: 'Sales Scriptwriter', category: 'Sales' },
  { id: 'screen-reader-agent', name: 'Screen Reader', category: 'Platform' },
  { id: 'seo-research', name: 'SEO Research', category: 'SEO' },
  { id: 'slack-summarizer', name: 'Slack Summarizer', category: 'Operations' },
  { id: 'storyboard-agent', name: 'Storyboard', category: 'Creative' },
  { id: 'system-auditor', name: 'System Auditor', category: 'Platform' },
  { id: 'tiktok-analytics-agent', name: 'TikTok Analytics', category: 'Analytics' },
  { id: 'tiktok-audio-researcher', name: 'TikTok Audio', category: 'Research' },
  { id: 'tiktok-frame-advisor', name: 'TikTok Frame Advisor', category: 'Creative' },
  { id: 'tiktok-growth-agent', name: 'TikTok Growth', category: 'Social' },
  { id: 'tiktok-scriptwriter', name: 'TikTok Scriptwriter', category: 'Content' },
  { id: 'tiktok-strategist', name: 'TikTok Strategist', category: 'Social' },
  { id: 'trend-forecasting', name: 'Trend Forecasting', category: 'Research' },
  { id: 'ui-ux-designer', name: 'UI/UX Designer', category: 'Creative' },
  { id: 'video-intelligence', name: 'Video Intelligence', category: 'Creative' },
  { id: 'video-script', name: 'Video Script', category: 'Content' },
  { id: 'viral-hook-tester', name: 'Viral Hook Tester', category: 'Content' },
  { id: 'web-developer', name: 'Web Developer', category: 'Engineering' },
  { id: 'web-researcher', name: 'Web Researcher', category: 'Research' },
  { id: 'webapp-builder', name: 'Webapp Builder', category: 'Engineering' },
  { id: 'youtube-monitor', name: 'YouTube Monitor', category: 'Research' },
  { id: 'youtube-scriptwriter', name: 'YouTube Scriptwriter', category: 'Content' },
  { id: 'youtube-seo-agent', name: 'YouTube SEO', category: 'SEO' },
  { id: 'youtube-strategist', name: 'YouTube Strategist', category: 'Social' },
]
